#!/bin/sh

trap 'rm -rf "TEMP_FILE"' EXIT
touch TEMP_FILE
line=$(cat TEMP_FILE |wc -l)

while ! $1 >> TEMP_FILE ; 
do sleep 2 ; 
done ; 
echo  "\033[42;30mSUCEED!\033[0m"
line=$(cat TEMP_FILE |wc -l)
